# Generated by Django 4.2.7 on 2023-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero_tel', models.CharField(max_length=10, unique=True)),
                ('ville', models.CharField(max_length=255)),
                ('id_inscription', models.CharField(default='IMOBDZFRA0C6879A', editable=False, max_length=20, unique=True)),
            ],
        ),
    ]
