# Generated by Django 4.2.7 on 2023-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0003_alter_inscription_id_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR7C7EFC15', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='numero_tel',
            field=models.CharField(max_length=10),
        ),
    ]
