# Generated by Django 4.2.7 on 2023-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0004_alter_inscription_id_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFRAB1AC42F', editable=False, max_length=20, unique=True),
        ),
    ]
