# Generated by Django 4.2.7 on 2023-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0006_alter_inscription_id_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR02ABB730', editable=False, max_length=20, unique=True),
        ),
    ]
